# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-17 02:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(verbose_name='Total charge')),
                ('status', models.IntegerField(choices=[(0, '\u0412 \u043f\u0440\u043e\u0446\u0435\u0441\u0441\u0435'), (1, '\u0412\u044b\u043f\u043e\u043b\u043d\u0435\u043d'), (2, '\u041e\u0448\u0438\u0431\u043a\u0430')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionContract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, '\u0412 \u043f\u0440\u043e\u0446\u0435\u0441\u0441\u0435'), (1, '\u0412\u044b\u043f\u043e\u043b\u043d\u0435\u043d'), (2, '\u0427\u0430\u0441\u0442\u0438\u0447\u043d\u043e \u0412\u044b\u043f\u043e\u043b\u043d\u0435\u043d'), (3, '\u041e\u0442\u043c\u0435\u043d\u0435\u043d')], default=0)),
                ('create_date', models.DateTimeField(auto_now=True)),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('rating_customer', models.PositiveIntegerField()),
                ('rating_responsibilities', models.PositiveIntegerField()),
                ('review', models.TextField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
