# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-17 05:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_auto_20171217_0224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactioncontract',
            name='rating_customer',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transactioncontract',
            name='rating_responsibilities',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
