# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-16 19:48
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.PositiveIntegerField(verbose_name='Total amount of contract')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Name of Contract')),
            ],
        ),
        migrations.CreateModel(
            name='Responsibility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Name of responsibility')),
                ('status', models.IntegerField(choices=[(0, '\u0412 \u043f\u0440\u043e\u0446\u0435\u0441\u0441\u0435'), (1, '\u0412\u044b\u043f\u043e\u043b\u043d\u0435\u043d'), (2, '\u041d\u0435 \u0432\u044b\u043f\u043e\u043b\u043d\u0435\u043d')], default=0)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Contract')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='balance',
            field=models.IntegerField(default=0, verbose_name='Balance of User'),
        ),
        migrations.AlterField(
            model_name='user',
            name=b'username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.ASCIIUsernameValidator()], verbose_name='username'),
        ),
        migrations.AddField(
            model_name='contract',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
