# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-16 20:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_auto_20171216_1948'),
    ]

    operations = [
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Name of good')),
                ('options', models.CharField(blank=True, max_length=255, verbose_name='Options of good')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Description of good')),
                ('image', models.FileField(blank=True, null=True, upload_to='good/images/', verbose_name='Description of good')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(verbose_name='Name of goods')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Good')),
                ('responsibility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Responsibility')),
            ],
        ),
    ]
