# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-17 02:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='responsibility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Responsibility'),
        ),
    ]
