# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-17 00:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='tmp_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='good',
            name='tmp_responsibility',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
